# Nombre (Integracion Continua)
name: CI

# Se declaran eventos
on:

 #Cada vez que se ejecute un push
 push:
 workflow_dispatch:

# Se declaran jobs y steps (jobs --< steps)
jobs:
  
 build:
   
  runs-on: ubuntu-latest
  
  steps:
   
   - uses: actions/checkout@v3
   
   - name: Run a multi-line script
     run: |
       echo "Hola mundo!"
 test:
  runs-on: ubuntu-latest
  needs: build
  steps:
   - name: test
     run: |
      echo "hola 2"
