# Nombre (Integracion Continua)
name: CI

# Se declaran eventos
on:

 #Cada vez que se ejecute un push
 push:
   #em la/s siguiente/s ramas
   branches: [ "main" ]
   
 workflow_dispatch:

# Se declaran jobs y steps (jobs --< steps)
jobs:
  
 build:
   
  runs-on: ubuntu-latest
  
  steps:
   
   - uses: actions/checkout@v3
   # Runs a set of commands using the runners shell
   - name: Run a multi-line script
     run: |
       Hola mundo.
